FROM adoptopenjdk/openjdk11:alpine-jre

LABEL maintainer=""

# RUN apk add --no-progress --no-cache tzdata=2019a-r0 \
#     && ls /usr/share/zoneinfo/Europe/ \
#     && cp /usr/share/zoneinfo/Europe/Oslo /etc/localtime \
#     && echo "Europe/Oslo" >  /etc/timezone \
#     && date \
#     && apk del --no-progress --no-network --no-cache tzdata

# Volumes are a mechanism to persist data generated by the container on the Host OS, and share directories from the Host OS with the container.
# Creating a mount point with path /tmp because this is where the spring boot application creates working directories for Tomcat by default.
# Although it is not required for this spring boot application because who cares about tomcat directories. But if you want to store stuff like tomcat access logs, then VOLUMES are very useful.
VOLUME /tmp

# Avoid running as root (not working on distroless)
#RUN groupadd nobody && useradd -g nobody app
#USER app
# Avoid running as root
RUN adduser -g nobody app --disabled-password
USER app
RUN date

# Add the application's jar file.
COPY target/*.jar app.jar

# To reduce Tomcat startup time we added a system property pointing to "/dev/urandom" as a source of entropy.
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-showversion","-jar","/app.jar"]
